### PR TITLE
get_output_schema exception with table name

### PR DESCRIPTION
**Pull request by AliSayyah**
get_output_schema will raise an exception with the name of the corresponding table if something goes wrong while generating the tables.
based on #447 

Another alternative would be to add the `errors` attribute to the  `OutputSchema` class and handle it like how warnings are being addressed.

### CODE REVIEW

**Comment by AliSayyah** [comment]
The test works in python 3.10 (and 3.9 in local) but not with 3.7.
I have to figure out what functionality changed in these versions.

**Comment by dantownsend** [comment]
I think something changed with mocks in > Python 3.7.

I've been caught out by this many times.

**Comment by AliSayyah** [comment]
https://docs.python.org/3/library/unittest.mock.html#unittest.mock.AsyncMock

I think this is it. `create_table_class_from_db` is an async function and mock handles it in `>=3.8` as a coroutine.

**Comment by dantownsend** [comment]
@AliSayyah If you search for `set_mock_return_value` in the Piccolo codebase, there's something there which should help.

**Comment by AliSayyah** [comment]
@dantownsend I think this is ready for review,

**Comment by dantownsend** [comment]
@AliSayyah Cool, thanks

**Comment by dantownsend** [comment]
@AliSayyah This looks great thanks.

I pushed a few extra commits:

 * I decided to use your `AsyncMock` implementation everywhere, and removed `set_mock_return_value`, as I think your solution is more intuitive.
 * I took this opportunity to improve error handling if indexes couldn't be parsed (related to https://github.com/piccolo-orm/piccolo/issues/363)

**Comment by AliSayyah** [comment]
Thank you this is great!

**Comment by dantownsend** [comment]
@AliSayyah Yeah, it could do with a unit test really. I'm happy to release as is, but if you wouldn't mind doing a separate PR to add a test, that would be great.

**Comment by AliSayyah** [comment]
> @AliSayyah Yeah, it could do with a unit test really. I'm happy to release as is, but if you wouldn't mind doing a separate PR to add a test, that would be great.

Yeah, I'll open another PR👍.

**Comment by dantownsend** [comment]
@AliSayyah thanks

**Pull request merged**
