### PR TITLE
add index reflection in schema generation

### PR DESCRIPTION
**Pull request by wmshort**

### CODE REVIEW

**Comment by wmshort** [comment]
@dantownsend Should be all set now...

**Comment by dantownsend** [comment]
@wmshort Thanks for this, it looks great. I just need to test it.

Annoyingly there are some merge conflicts now - it's my fault for merging something in earlier. I think they're pretty minor though.

**Comment by wmshort** [comment]
> @wmshort Thanks for this, it looks great. I just need to test it.
> 
> Annoyingly there are some merge conflicts now - it's my fault for merging something in earlier. I think they're pretty minor though.

No worries, we can take care of those quickly I think

**Comment by dantownsend** [comment]
Closing for now, as it's replaced by https://github.com/piccolo-orm/piccolo/pull/282

**Pull request closed without merging**
