### PR TITLE
added create method

### PR DESCRIPTION
**Pull request by AliSayyah**
based on this issue  #238

### CODE REVIEW

**Comment by dantownsend** [comment]
@AliSayyah Thanks for this - looks great. Just need to update the docs, and I think it's done.

**Comment by AliSayyah** [comment]
@dantownsend I couldn't find the related docs for this.
If you provide a link to the corresponded doc, I'll update it.

**Comment by dantownsend** [comment]
Maybe just a little section here?

https://github.com/piccolo-orm/piccolo/blob/master/docs/src/piccolo/query_types/objects.rst#creating-objects

**Comment by AliSayyah** [comment]
> Maybe just a little section here?
> 
> https://github.com/piccolo-orm/piccolo/blob/master/docs/src/piccolo/query_types/objects.rst#creating-objects

Haven't seen that. Thank you

**Comment by dantownsend** [comment]
@AliSayyah Looks great, thanks!

**Pull request merged**
