### PR TITLE
1108 Be able to pass an engine into `TableStorage`

### PR DESCRIPTION
**Pull request by dantownsend**
Resolves https://github.com/piccolo-orm/piccolo/issues/1108

### CODE REVIEW

**Comment by sinisaos** [comment]
@dantownsend When you merge this PR, can you please close [this old PR](https://github.com/piccolo-orm/piccolo/pull/875) that basically did the same thing. Thanks.

**Comment by dantownsend** [comment]
@sinisaos Ah, sorry - I completely forgot about that one.

They are slightly different in that this one passes engine into `__init__`, and the other one passes it into `reflect`. Which do you prefer?

**Comment by sinisaos** [comment]
@dantownsend I think both versions are fine, but I prefer your version, because I think it's more common to pass config arguments in constructor, than in methods.

**Comment by dantownsend** [comment]
@sinisaos Thanks - lets go with this for now then.

**Pull request merged**
