### PR TITLE
max password length

### PR DESCRIPTION
**Pull request by dantownsend**
Added a max password length check to `BaseUser`.

### CODE REVIEW

**Comment by sinisaos** [comment]
@dantownsend Could you also add `min_length` password checker?

**Review by yezz123 — APPROVED** [review]
Good Ad-dons, its better to documented the use case of it 🚀

**Comment by dantownsend** [comment]
@sinisaos Good idea - I'll add it.

@yezz123 Thanks, I'll add docs for it. The reason I added it is if someone uses a huge password, it takes longer to hash.

**Comment by dantownsend** [comment]
@sinisaos I'll add min password length in a future PR.

**Comment by sinisaos** [comment]
@dantownsend I later realized that this may not be so necessary because we cannot pass a password shorter than 4 characters when creating a user. https://github.com/piccolo-orm/piccolo/blob/2d207d8f8a1ea501016337aea692e59461133301/piccolo/apps/user/commands/create.py#L79

You can do a `min_length` password checker in the `login` method or you don't have to, as you wish.

**Comment by dantownsend** [comment]
@sinisaos Cool, thanks.

**Pull request merged**
