### PR TITLE
Inline Variables that immediately returned & Refactor Multipart of Codes ✨

### PR DESCRIPTION
**Pull request by yezz123**
During this week, I work with Piccolo to build a new Project, I found the code that is great & Friendly, also Why not helping the team to build a clean Code 👨‍💻 , so I start reading the code and refactor it.

- I found that the multiple things are the none inlined Variable: in the case when the variable being declared is immediately returned.
- Also the issue relates to Moves statements or the *Hoist statements out of if*.
- Other issues relate to using `any()` and other ones ...

### CODE REVIEW

**Comment by dantownsend** [comment]
@yezz123 Thanks for this - took me a while to go through it, but it all makes sense, and looks great.

You must have a super linter, or else you have super linting skills!

**Comment by yezz123** [comment]
> @yezz123 Thanks for this - took me a while to go through it, but it all makes sense and looks great.
> 
> You must have a super linter, or else you have super linting skills!

@dantownsend Just Documentation & some previous experience in Linting and Clean Code 😅

**Comment by AliSayyah** [comment]
@yezz123 wow good job!

**Comment by pinchXOXO** [comment]
@yezz123 This is a Great PR! 🚀

**Pull request merged**
