### PR TITLE
create multiple tables at once 

### PR DESCRIPTION
**Pull request by AliSayyah**
This PR adds the function described in this issue #233 and a unit test to test it out.

### CODE REVIEW

**Comment by AliSayyah** [comment]
`sqlite3.OperationalError: near "CASCADE": syntax error`
It seems that SQLite3 doesn't support CASCADE.

**Comment by dantownsend** [comment]
@AliSayyah That might be a separate bug. For now, just leave out `cascade=True`, and it should be OK.

**Comment by AliSayyah** [comment]
> @AliSayyah That might be a separate bug. For now, just leave out `cascade=True`, and it should be OK.

in that case, it fails the Postgres tests.
I think resolving this issue with try/except to cover both cases would be enough for now.

**Comment by dantownsend** [comment]
It looks great.

The only thing I'm not sure about is where `create_tables` should live. I originally thought about it being in `piccolo/tables.py`, but not sure if that causes circular dependency issues (due to `sort_table_classes`).

**Comment by AliSayyah** [comment]
> It looks great.
> 
> The only thing I'm not sure about is where `create_tables` should live. I originally thought about it being in `piccolo/tables.py`, but not sure if that causes circular dependency issues (due to `sort_table_classes`).

yes, I tried that and you are right. it causes circular import. the current module is not very related to the function but I couldn't find a better place.

**Comment by dantownsend** [comment]
I don't mind moving `sort_table_classes` - as it's more broadly applicable than just migrations.

`sort_table_classes` could live in `tables.py` or a new file in `piccolo/utils`, if that fixes the circular import problem.

**Comment by AliSayyah** [comment]
> I don't mind moving `sort_table_classes` - as it's more broadly applicable than just migrations.
> 
> `sort_table_classes` could live in `tables.py` or a new file in `piccolo/utils`, if that fixes the circular import problem.

ok, that's better. I'll see what works best.

**Comment by AliSayyah** [comment]
I think it's cleaner now. if it's alright now, I can update the docs too.

**Comment by dantownsend** [comment]
@AliSayyah Yeah, I like that - thanks.

For the docs, just a short section at the end of this page should be OK I guess:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_types/create_table.html

**Comment by dantownsend** [comment]
@AliSayyah Perfect, thanks!

**Comment by AliSayyah** [comment]
@dantownsend 
Thank you for creating this amazing project.
I had a wonderful experience contributing and helping a little bit.
And I would like to help out more. we can have a conversation about how can I be more helpful if it's okay with you.

**Comment by dantownsend** [comment]
@AliSayyah Thanks for the kind words, and your contributions.

You're welcome to contribute more - you can take a look at the issues, and I'll try and add some more with ideas I've had for improvements.

Also, if you have any ideas about how to improve the project I'd like to hear them.

**Pull request merged**
