### PR TITLE
1103 Improve arrow function

### PR DESCRIPTION
**Pull request by dantownsend**
Resolves https://github.com/piccolo-orm/piccolo/issues/1103

### CODE REVIEW

**Comment by sinisaos** [comment]
@dantownsend It seems that when we use the arrow function we need `strings` for queries (not `booleans` or other types). I think that makes sense because querystring uses strings. If we change the data type to string in these tests, everything passes. 
```python
def test_arrow_where(self):
    """
    Make sure the arrow function can be used within a WHERE clause.
    """
    RecordingStudio(
        name="Abbey Road", facilities='{"mixing_desk": true}'
    ).save().run_sync()

    self.assertEqual(
        RecordingStudio.count()
        .where(RecordingStudio.facilities.arrow("mixing_desk").eq("true")) # <-- here
        .run_sync(),
        1,
    )

    self.assertEqual(
        RecordingStudio.count()
        .where(RecordingStudio.facilities.arrow("mixing_desk").eq("false")) # <-- here
        .run_sync(),
        0,
    )
```
I also removed the [load json test](https://github.com/piccolo-orm/piccolo/blob/e2fa8f89f94bc995722ca42db856d9aad6471a46/tests/columns/test_jsonb.py#L158C9-L167C50) because the `output(load_json=True)` doesn't return a boolean after new changes.

I hope that makes sense.

**Comment by dantownsend** [comment]
@sinisaos Thanks - you're right, the JSON values have to be strings.

**Review by sinisaos — APPROVED** [review]
@dantownsend I think this is a great enhancement :+1:

**Comment by dantownsend** [comment]
@sinisaos Thanks. I went a bit crazy on this in the end.

You can now go multiple levels deep, and traverse array elements within the JSON.

```python
await RecordingStudio.select(
    RecordingStudio.facilities["a"]["b"][0]["c"]
)
```

**Comment by sinisaos** [comment]
@dantownsend Wow! It's really amazing.

**Comment by dantownsend** [comment]
@sinisaos Thanks. It turned into a bigger thing than I expected. But with this, we can potentially do better JSON filtering in Piccolo Admin.

**Pull request merged**
