### PR TITLE
Create users with CLI arguments 

### PR DESCRIPTION
**Pull request by AliSayyah**
necessary changes to add the functionality that was requested in #196.
also, a new unit test has been added for testing it.

### CODE REVIEW

**Comment by dantownsend** [comment]
@AliSayyah This is great thanks! I've just updated the docs to reflect the change.

**Comment by dantownsend** [comment]
Fixes https://github.com/piccolo-orm/piccolo/issues/196

**Comment by AliSayyah** [comment]
> @AliSayyah This is great thanks! I've just updated the docs to reflect the change.

thank you for your help!
I'm looking forward to more contributions.
if there is a certain thing on your mind, I can get onto it.

**Comment by dantownsend** [comment]
@AliSayyah No problem.

Here are a couple of issues which might be interesting to work on:

https://github.com/piccolo-orm/piccolo/issues/232
https://github.com/piccolo-orm/piccolo/issues/233

Thanks!

**Pull request merged**
