### PR TITLE
Add preliminary support for choices

### PR DESCRIPTION
**Pull request by cheesycod**

### CODE REVIEW

**Comment by cheesycod** [comment]
This PR adds preliminary support for choices as per the issue I made, it supports both a nested tuple of choices and a enum

**Comment by dantownsend** [comment]
Thanks for this - I used it as inspiration for this MR:

https://github.com/piccolo-orm/piccolo/pull/105

Here are some docs for what has been added:

https://github.com/piccolo-orm/piccolo/blob/94b22417bec28ed75b16e2bd7202d281d5e1445c/docs/src/piccolo/schema/advanced.rst#choices

**Comment by cheesycod** [comment]
Thanks

**Comment by dantownsend** [comment]
Closing, as was used as the foundation for another PR, thanks!

**Pull request closed without merging**
