### PR TITLE
Addition of templates

### PR DESCRIPTION
**Pull request by AbhijithGanesh**
Addresses Issue #264

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
Can you please merge this @dantownsend

**Comment by dantownsend** [comment]
@AbhijithGanesh I'm a bit swamped at the moment, but will review as soon as I can.

**Comment by dantownsend** [comment]
@AbhijithGanesh Thanks for this.

I simplified the templates a bit, as I want to keep things quite simple while we test this new functionality.

We can add more functionality back as we become more experienced with it.

**Comment by AbhijithGanesh** [comment]
Yes Daniel, I agree

**Pull request merged**
