### PR TITLE
Add returning clause for delete operation

### LINKED ISSUE #698: Getting number of affected rows
With some operations, postgres returns the number of affected/processed rows. Other ORMs make that information available. My use case is for deletions, but perhaps it would be nice to have this in general.
I haven't looked at the codebase, but how hard would that be to implement? I might give that a try if it's not too complicated.

### PR DESCRIPTION
**Pull request by waldner**
Should fix #698 .

### CODE REVIEW

**Comment by dantownsend** [comment]
@waldner This looks great, thanks!

I just a minor tweak to skip the test for older versions of SQLite. Once the CI has finished will merge it in.

**Comment by waldner** [comment]
> I just made a minor tweak to skip the test for older versions of SQLite.

Argh, I missed that bit! Thanks!

**Comment by waldner** [comment]
Any chances this will make it to a release anytime soon?

**Comment by dantownsend** [comment]
Yeah, will release it now.

**Comment by dantownsend** [comment]
It's available in version `0.99.0`:

https://pypi.org/project/piccolo/0.99.0/

**Pull request merged**
