### PR TITLE
Support `DISTINCT` with `COUNT`

### LINKED ISSUE #826: Support `COUNT DISTINCT`
This feature is useful in certain circumstances.
For example, counting how many tags which are actually used in `tag_to_book` table (instead of counting all created tags in `tag` table).

### PR DESCRIPTION
**Pull request by lqmanh**
Resolves #826.

### CODE REVIEW

**Comment by dantownsend** [comment]
Thanks a lot for this - looks like the SQLite tests are failing for some reason.

**Comment by lqmanh** [comment]
@dantownsend Could you take a look?

**Comment by dantownsend** [comment]
@lqmanh Yes, sorry - will get to this soon. Just finishing off another PR and will look at this one next.

**Comment by dantownsend** [comment]
@lqmanh It looks good. I have some ideas for a tweaked API - you can see it here:

https://github.com/piccolo-orm/piccolo/pull/836

It's based off your PR. I just changed it from `MyTable.count().distinct(on=[...])` to `MyTable.count(distinct=[...])`. The `distinct` delegate needed us to do some stuff with the order by clause, so I bypassed it. What do you think?

**Comment by lqmanh** [comment]
@dantownsend That's nice, thanks. I chose `.count().distinct()` just for the consistency with `.select().distinct()`. I don't mind alternatives though.

I guess we can close this PR and complete our work with your new PR instead.

**Pull request closed without merging**
