### PR TITLE
include index info in schema generation (replaces #278)

### PR DESCRIPTION
**Pull request by wmshort**
@dantownsend Somehow I managed to royally botch a commit and this has screwed with the tests. Starting the PR from scratch seemed easier.

### CODE REVIEW

**Comment by dantownsend** [comment]
@wmshort No worries - if there's anything I can help with let me know.

**Comment by wmshort** [comment]
> @wmshort No worries - if there's anything I can help with let me know.

Can you check the test logs? I can't for the life of me figure out what I have done to screw things up. Sorry :/

**Comment by dantownsend** [comment]
@wmshort No problem, I'll investigate.

**Comment by dantownsend** [comment]
@wmshort  This one is a bit of a head scratcher. Sorry it took so long. I worked out why the tests were failing.

The unique value for the column was being set in two separate places, and they were conflicting.

https://github.com/piccolo-orm/piccolo/blob/7c086af5fab955b6c633833c5e3b93503d49f697/piccolo/apps/schema/commands/generate.py#L651

https://github.com/piccolo-orm/piccolo/blob/7c086af5fab955b6c633833c5e3b93503d49f697/piccolo/apps/schema/commands/generate.py#L657

It's because there are unique indexes, and unique constraints - it's possible for a column to have one and not the other.

I let the unique constraint take precedence for now, but might merit more investigation.

**Comment by wmshort** [comment]
@dantownsend good catch and I think your solution is the right one. The StackOverflow answers didn't really clarify things for me but the docs seem clear enough: the unique index is consequent on the unique constraint -- it is created automatically for the unique constraint. I guess this means you could have a unique index that is independent of any unique constaint but if you have a unique constraint or PK then you will have a unique index on it as the enforcement mechanism.

**Comment by dantownsend** [comment]
@wmshort Cool, I'm happy with it then. I just added a quick unit test.

@AliSayyah Do you have any thoughts on this, as you did a lot of the reflection stuff?

**Pull request merged**
