### PR TITLE
multiple arguments in WHERE clause

### PR DESCRIPTION
**Pull request by AliSayyah**
WHERE clause now will support multiple arguments(and no argument) based on discussion #237
I think testing needs to be extended to other methods too.
just want to know your idea before moving on to that.

### CODE REVIEW

**Comment by dantownsend** [comment]
@AliSayyah It looks great to me.

**Comment by AliSayyah** [comment]
> @AliSayyah It looks great to me.

Ok, nice.

**Comment by AliSayyah** [comment]
@dantownsend Updated the docs.

**Comment by dantownsend** [comment]
@AliSayyah This is great - thanks!

**Pull request merged**
